# Generated by Django 4.2.15 on 2024-09-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='show_color',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='show_size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='show_stock',
            field=models.BooleanField(default=True),
        ),
    ]
