# Generated by Django 4.2.15 on 2024-09-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_discountcode_delete_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='show_stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
