# Generated by Django 4.2.15 on 2024-09-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_color_size_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sizes',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
