# Generated by Django 4.2.15 on 2024-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_productvariant_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
