# Generated by Django 4.2.15 on 2024-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_inventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
