# Generated by Django 4.2.15 on 2024-09-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_inventory_previous_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='ajio',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='amazon',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='flipkart',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='myntra',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
