# Generated by Django 4.2.15 on 2024-09-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_inventory_ajio_inventory_amazon_inventory_flipkart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='previous_price',
        ),
    ]
