# Generated by Django 4.2.15 on 2024-09-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
