# Generated by Django 4.2.15 on 2024-09-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_cartitem_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='final_price',
        ),
    ]
