# Generated by Django 4.2.15 on 2024-09-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_cart_updated_at_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='taxes',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
