# Generated by Django 4.2.15 on 2024-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
