# Generated by Django 4.2.15 on 2024-09-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash_on_delivery', max_length=30),
        ),
    ]
