# Generated by Django 4.2.15 on 2024-10-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_productvariant_original_price_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='original_price_usd',
            new_name='original_price',
        ),
    ]
