# Generated by Django 4.2.15 on 2024-10-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_rename_original_price_usd_productvariant_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='used_count',
        ),
    ]
