# Generated by Django 4.2.15 on 2024-10-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_remove_discountcode_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
