# Generated by Django 4.2.15 on 2024-10-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_remove_rating_product_rating_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='order',
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.product'),
            preserve_default=False,
        ),
    ]
