# Generated by Django 4.2.15 on 2024-10-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.rating'),
        ),
    ]
