# Generated by Django 4.2.15 on 2024-10-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Rating',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.rating'),
        ),
    ]
