# Generated by Django 4.2.15 on 2024-10-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
