# Generated by Django 4.2.15 on 2024-10-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_remove_amazonproduct_amazon_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myntraproduct',
            name='myntra_id',
        ),
        migrations.RemoveField(
            model_name='myntraproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='myntraproduct',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='myntraproduct',
            name='variant',
        ),
        migrations.AddField(
            model_name='myntraproduct',
            name='brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myntraproduct',
            name='image',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myntraproduct',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myntraproduct',
            name='url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myntraproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
