# Generated by Django 4.2.15 on 2024-10-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_remove_ajioproduct_ajio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajioproduct',
            name='url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
